source :rubygems

gem 'cramp'

# Async webserver for running a cramp application
gem 'thin'

# Rack based routing
gem 'http_router'

# Collection of async-proof rack middlewares - https://github.com/rkh/async-rack.git
gem 'async-rack'

# For async Active Record models
# gem 'mysql2', '~> 0.2.11'
# gem 'activerecord'

# Using Fibers + async callbacks to emulate synchronous programming
# gem 'em-synchrony'

# Generic interface to multiple Ruby template engines - https://github.com/rtomayko/tilt
gem 'tilt', '1.3.2'
gem 'haml', '3.1.2'

group :test do
	gem 'capybara', '~>1.0.1'
	gem 'cucumber'
	gem 'rspec-cramp'
  # Development gems
  # gem 'ruby-debug19'
end
